[package]
name = "umdb-rest-example"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.6.4"
actix-web = "4.4.0"
env_logger = "0.10.0"
log = "0.4.20"
serde = "1.0.188"
serde_json = "1.0.105"
tokio = "1.32.0"
umdb = { path = "../../umdb" }
